// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezeonofoozfhishwlami.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZW9ub2Zvb3pmaGlzaHdsYW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTMzODYsImV4cCI6MjA2MzA4OTM4Nn0.x9F1vvzztFyoXl8AMycUH7eLIU3Zxalx1zCQ8BYCTIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);